nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']  # Le domaine de ton frontend
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
